FROM node:14.17.0 AS development

# Create app directory
WORKDIR /app/pog_server

## 프로젝트의 모든 파일을 WORKDIR(/app)로 복사한다
COPY . .


# Docker 추가적인 공부 필요.

# Copy important files - Add ormconfig.ts here if using Typeorm
# COPY .eslintrc.js nest-cli.json tsconfig.json tsconfig.build.json ./

# Copy env
# COPY .env /app/pog_server/.env

RUN npm ci

# Add storage folder to the container (If you want to add other folder contents to the container)
# ADD storage /var/www/backend/storage

# Entrypoint command - Replace `"yarn"` with `"npm", "run"` if you are using NPM as your package manager.
# You can update this to run other NodeJS apps
CMD [ "npm", "run", "start"]