FROM node:14-alpine AS build

# Create app directory
WORKDIR /app/pog_server

COPY package*.json /app/pog_server/
RUN npm ci
COPY . /app/pog_server/
RUN npm run build



FROM node:14-alpine

ENV NODE_ENV=development
WORKDIR /app/pog_server

COPY --from=build /app/pog_server/dist /app/pog_server/dist
COPY --from=build /app/pog_server/node_modules /app/pog_server/node_modules
COPY --from=build /app/pog_server/package.json /app/pog_server/package.json
# Add storage folder to the container (If you want to add other folder contents to the container)
# ADD storage /var/www/backend/storage

EXPOSE 3000
ENTRYPOINT [ "node" ]
CMD [ "dist/apps/api/src/main.js" ]